accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name= 'accounts'

urlpatterns=[
    path('signup', views.signup, name='signup'),
    path('login', auth_views.login,{'template_name': 'accounts/login.html'}, name='login'),
    path('logout', auth_views.logout, name='logout'),
]

products/urls.py
from django.urls import path
from . import views
app_name = 'products'
urlpatterns=[
    # path('', views.products_view, name='products_view'),
    path('create', views.product_create, name='product_create'),
    path('all_products', views.all_products, name='all_products'),
    path('delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('productss/<int:id>/', views.product_url, name='product_url'),
    path('products_view', views.products_view, name='products_view'),
    path('product_update/<int:id>/', views.product_update, name='product_update'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace="products")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

class Product(models.Model):
    title=models.CharField(max_length=20)
    description=models.TextField()
    price=models.DecimalField(decimal_places=2, max_digits=100)
    summary=models.TextField(default='This is cool')

    class Meta:
        db_table= 'prod'

    def __str__(self):
        return self.title

products/forms.py
from django import forms
from .models import Product

# class product_form(forms.Form):
#     title=forms.CharField(required=False,
#     widget=forms.TextInput(
#         attrs={
#             'placeholder': 'enter your title'
#         }
#     ))
#     description=forms.CharField()
#     price=forms.DecimalField()
#     summary=forms.CharField

class product_form(forms.ModelForm):
    class Meta:
        model=Product
        fields=['title','description', 'price','summary']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

def signup(request):
    if request.method=='POST':
        form= UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            raw_password=form.cleaned_data.get('password1')
            user=authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('login')

    else:
        form=UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home_view(request):
    context={
        "text" : "my title",
        "number" : [123, 546, 121]
    }
    return render(request, 'home.html', context)

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Product
from .forms import product_form
from django.contrib.auth.decorators import login_required

@login_required
def products_view(request):
    objs=Product.objects.get(id=16)
    context={
        'title' :objs.title,
        'description': objs.description
    }

    return render(request, "products_details.html", context)
@login_required
def all_products(request):
    all_products=Product.objects.all().order_by('title')
    context={
        'all_products': all_products,
    }
    return render (request, 'all_products.html', context)
@login_required
def product_create(request):
    if request.method=='POST':
        form=product_form(request.POST or None)
        if form.is_valid():
            Product.objects.create(**form.cleaned_data)
            msg = 'saved successful'
            messages.add_message(request, messages.INFO, msg)
            context={
            'form': form,
        }
            
            return render(request, 'product_create.html', context)

    else:
        form=product_form()
        context={
            'form': form
        }

        return render(request, 'product_create.html', context)

@login_required
def product_update(request, id):
    objct=get_object_or_404(Product, id=id)
    if request.method=='POST':
        form=product_form(request.POST, instance=objct)
        if form.is_valid():
            Product.objects.filter(pk=id).update_or_create(**form.cleaned_data)
            context={
                'form':form
            }
            return render(request, 'product_update.html', context)

    else:
        form=product_form(instance=objct)
        context={
            'form': form
        }
        return render(request, 'product_update.html', context)

@login_required
def delete_product(request, id):
    objct=Product.objects.get(id=id)
    objct.delete()
    return redirect('products:all_products')
    all_products=Product.objects.all()
    context={
        'all_products':all_products
    }
    return render(request, 'all_products.html', context)

     
from django.http import Http404
@login_required
def product_url(request, id):
    try:
        obj=Product.objects.get(id=id)
        context={
            'objects': obj
        }
        return render(request, 'products_details.html', context)
    except Product.DoesNotExist:
        raise Http404("product does not exist")

    return render(request, 'products_details.html', context)

templates/accounts/login.html
{% extends 'base.html' %}
{% block title%}Login {% endblock %}
{% block content %}
<h2>Login</h2>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
<button type="submit">Login</button>
</form>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Signup</button>
</form>
{% endblock %}

templates/all_products.html
{% extends 'base.html' %}
<!-- {% include 'navbar.html' %} -->
{% block content %}
{% for product in all_products %}
<div>
    {{product.id}}<button><a href="{% url 'products:delete_product' product.id %}">Delete</a></button>
   <button><a href="{% url 'products:product_update' product.id %}">Edit</a></button>

</div>
{% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <!-- {% load static %} -->

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png'%}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  {% block title %}
    My title
  {% endblock %}

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'assets/demo/demo.css'%}" rel="stylesheet" />
</head>

<body class="dark-edition">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="black" data-image="{% static 'assets/img/sidebar-2.jpg'%}">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
        <a href="http://www.creative-tim.com" class="simple-text logo-normal">
          Products Dashboard
        </a>
      </div>
      {% include 'sidebar.html' %}
      <!-- side bar -->

    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top " id="navigation-example">
        <!-- navbar -->
        {% include 'navbar.html' %}
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
         {% block content %}
         {% endblock %}

     
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  Creative Tim
                </a>
              </li>
              <li>
                <a href="https://creative-tim.com/presentation">
                  About Us
                </a>
              </li>
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
              <li>
                <a href="https://www.creative-tim.com/license">
                  Licenses
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right" id="date">
            , made with <i class="material-icons">favorite</i> by
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
          </div>
        </div>
      </footer>
      <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;
      </script>
    </div>
  </div>
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Filters</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger active-color">
            <div class="badge-colors ml-auto mr-auto">
              <span class="badge filter badge-purple active" data-color="purple"></span>
              <span class="badge filter badge-azure" data-color="azure"></span>
              <span class="badge filter badge-green" data-color="green"></span>
              <span class="badge filter badge-warning" data-color="orange"></span>
              <span class="badge filter badge-danger" data-color="danger"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="header-title">Images</li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="{% static 'assets/img/sidebar-1.jpg'%}" alt="">
          </a>
        </li>
        <li class="active">
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="{% static 'assets/img/sidebar-2.jpg'%}" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="{% static 'assets/img/sidebar-3.jpg'%}" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="{% static 'assets/img/sidebar-4.jpg'%}" alt="">
          </a>
        </li>
        <li class="button-container">
          <a href="https://www.creative-tim.com/product/material-dashboard-dark" target="_blank" class="btn btn-primary btn-block">Free Download</a>
        </li>
        <!-- <li class="header-title">Want more components?</li>
            <li class="button-container">
                <a href="https://www.creative-tim.com/product/material-dashboard-pro" target="_blank" class="btn btn-warning btn-block">
                  Get the pro version
                </a>
            </li> -->
        <li class="button-container">
          <a href="https://demos.creative-tim.com/material-dashboard-dark/docs/2.0/getting-started/introduction.html" target="_blank" class="btn btn-default btn-block">
            View Documentation
          </a>
        </li>
        <li class="button-container github-star">
          <a class="github-button" href="https://github.com/creativetimofficial/material-dashboard/tree/dark-edition" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star ntkme/github-buttons on GitHub">Star</a>
        </li>
        <li class="header-title">Thank you for 95 shares!</li>
        <li class="button-container text-center">
          <button id="twitter" class="btn btn-round btn-twitter"><i class="fa fa-twitter"></i> &middot; 45</button>
          <button id="facebook" class="btn btn-round btn-facebook"><i class="fa fa-facebook-f"></i> &middot; 50</button>
          <br>
          <br>
        </li>
      </ul>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js'%}"></script>
  <script src="{% static 'assets/js/core/bootstrap-material-design.min.js' %}"></script>
  <script src="https://unpkg.com/default-passive-events"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="{% static 'assets/js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/material-dashboard.js' %}"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'assets/demo/demo.js' %}"></script>
  <!-- <script src="{% static 'js/classie.js' %}"></script> -->
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% block content%}
<h1>This is a template</h1>
{{request.user}}
<p>How is the template</p>

<p>
    {{ text }}
</p>
<ul>
{% for numb in number  %}
<li> {{forloop.counter}} - {{numb}}</li>
{% endfor %}
</ul>

{% endblock%}

templates/navbar.html
<div class="container-fluid">
        <div class="navbar-wrapper">
          <a class="navbar-brand" href="javascript:void(0)">Dashboard</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon icon-bar"></span>
          <span class="navbar-toggler-icon icon-bar"></span>
          <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
          <form class="navbar-form">
            <div class="input-group no-border">
              <input type="text" value="" class="form-control" placeholder="Search...">
              <button type="submit" class="btn btn-default btn-round btn-just-icon">
                <i class="material-icons">search</i>
                <div class="ripple-container"></div>
              </button>
            </div>
          </form>
          <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li><a href="{%url 'products:all_products' %}">All products</a>
                </li>
                <li><a href="{% url 'products:product_create' %}">Create products</a></li>
                {% else %}
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% endif %}
                
          </ul>
        </div>
      </div>

templates/product_create.html
{% extends 'base.html' %}
{% block content %}

{% if messages %}
    {% for message in messages %}
    {% if 'error' in message.tags %}
        <div id="messages" class="alert alert-danger fade in">
        <span class="close" data-dismiss="alert">×</span>
        <i class="fa fa-info fa-2x pull-left"></i>
    {% else %}
        <div id="messages" class="alert alert-success fade in">
        <span class="close" data-dismiss="alert">×</span>
        <i class="fa fa-check fa-2x pull-left"></i>
    {% endif %}    
        <p>{{ message }}</p>
    </div>
   {% endfor %}
{% endif %}
    <div id="message" class="alert alert-success fade in" style="display: none">
        <span class="close" data-dismiss="alert">×</span>
        <i class="fa fa-check fa-2x pull-left"></i>
  
        <span id="response"></span>
    </div>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save"/>
</form>
{% endblock %}

templates/product_update.html
{% extends 'base.html'%}
<h1>Edit records</h1>
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit" >Submit</button>
</form>

{% endblock %}

templates/products_details.html
{% extends 'base.html' %}
{% block content%}
<h1>saved product</h1>
{{request.user}}
<p>How is the template</p>

<p>
   {{objects}}
</p>


{% endblock%}

templates/sidebar.html
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item active  ">
            <a class="nav-link" href="./dashboard.html">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./user.html">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./tables.html">
              <i class="material-icons">content_paste</i>
              <p>Table List</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./typography.html">
              <i class="material-icons">library_books</i>
              <p>Typography</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./icons.html">
              <i class="material-icons">bubble_chart</i>
              <p>Icons</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./map.html">
              <i class="material-icons">location_ons</i>
              <p>Maps</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./notifications.html">
              <i class="material-icons">notifications</i>
              <p>Notifications</p>
            </a>
          </li>
          <!-- <li class="nav-item active-pro ">
                <a class="nav-link" href="./upgrade.html">
                    <i class="material-icons">unarchive</i>
                    <p>Upgrade to PRO</p>
                </a>
            </li> -->
        </ul>
      </div>